export enum Logs {
    // Registration & Email
    REGISTRATION = 'REGISTRATION',
    EMAIL_VERIFIED = 'EMAIL_VERIFIED',
    USER_REGISTERED = 'USER_REGISTERED',
    USER_CHANGED_EMAIL = 'USER_CHANGED_EMAIL',
    OTP_SENT = 'OTP_SENT',
    OTP_SEND_FAILED = 'OTP_SEND_FAILED',

    // Authentication
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILED = 'LOGIN_FAILED',
    LOGOUT = 'LOGOUT',

    // Password Management
    PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
    PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
    PASSWORD_CHANGED = 'PASSWORD_CHANGED',

    // Profile
    PROFILE_UPDATED = 'PROFILE_UPDATED',

    // Security Events
    UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
    TOKEN_BLACKLISTED = 'TOKEN_BLACKLISTED',
    RBAC_DENIED = 'RBAC_DENIED',
    RBAC_AUTHORIZED = 'RBAC_AUTHORIZED',
    ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
    ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED',
    ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
    ACCOUNT_TERMINATED = 'ACCOUNT_TERMINATED',
    ACCOUNT_REACTIVATED = 'ACCOUNT_REACTIVATED',

    // Admin Actions
    ADMIN_CREATED_USER = 'ADMIN_CREATED_USER',
    ADMIN_ANNOUNCE_ALL = 'ADMIN_ANNOUNCE_ALL',
    ROLE_CHANGED = 'ROLE_CHANGED',
    ADMIN_ANNOUNCE_ROLE = 'ADMIN_ANNOUNCE_ROLE',
    ADMIN_DELETE_USER = 'ADMIN_DELETE_USER',
    ADMIN_FORCE_LOGOUT = 'ADMIN_FORCE_LOGOUT',
    ADMIN_USER_LOCK = 'ADMIN_USER_LOCK',
    ADMIN_USER_UNLOCK = 'ADMIN_USER_UNLOCK',
    ADMIN_USER_SUSPEND = 'ADMIN_USER_SUSPEND',
    ADMIN_USER_TERMINATE = 'ADMIN_USER_TERMINATE',
    ADMIN_STATUS_CHANGE = 'ADMIN_STATUS_CHANGE',

    // Data Operations
    DATA_EXPORT = 'DATA_EXPORT',
    DATA_BACKUP_STARTED = 'DATA_BACKUP_STARTED',
    DATA_BACKUP_COMPLETED = 'DATA_BACKUP_COMPLETED',
    DATA_BACKUP_FAILED = 'DATA_BACKUP_FAILED',
    DATA_BACKUP_TEST_STARTED = 'DATA_BACKUP_TEST_STARTED',
    DATA_BACKUP_TEST_COMPLETED = 'DATA_BACKUP_TEST_COMPLETED',
    DATA_BACKUP_TEST_FAILED = 'DATA_BACKUP_TEST_FAILED',

    // Course Events
    COURSE_CREATED = 'COURSE_CREATED',
    COURSE_UPDATED = 'COURSE_UPDATED',
    COURSE_DELETED = 'COURSE_DELETED',
    COURSE_ARCHIVED = 'COURSE_ARCHIVED',
    COURSE_ENROLLED = 'COURSE_ENROLLED',
    COURSE_COMPLETED = 'COURSE_COMPLETED',
    COURSE_UNENROLLED = 'COURSE_UNENROLLED',

    // Quiz Events
    QUIZ_CREATED = 'QUIZ_CREATED',
    QUIZ_ATTEMPTED = 'QUIZ_ATTEMPTED',
    QUIZ_COMPLETED = 'QUIZ_COMPLETED',

    // Communication
    NOTIFICATION_SENT = 'NOTIFICATION_SENT',
    ANNOUNCEMENT_SENT = 'ANNOUNCEMENT_SENT',
    CHAT_MESSAGE_SENT = 'CHAT_MESSAGE_SENT',
    FORUM_POST_CREATED = 'FORUM_POST_CREATED',

    // Feedback
    FEEDBACK_SUBMITTED = 'FEEDBACK_SUBMITTED',
}